// GENERATED by scripts/product.mjs from ProvisioningStep, engine-manifest.json,
// PreflightInspection.Rows and CommandLine.HelpText — do not edit by hand. Regenerated on
// every build (DD159): every count the copy states, and the help text an excerpt slices.
import type { ProductData } from "./product-types";

export const product: ProductData = {
  "provisioning": {
    "steps": 11,
    "acquire": [
      "rootfs",
      "engine",
      "cli",
      "compose",
      "buildx"
    ]
  },
  "artefacts": {
    "count": 5,
    "versions": {
      "rootfs": "3.24.1",
      "engine": "29.7.2",
      "cli": "29.7.2",
      "compose": "5.4.0",
      "buildx": "0.36.1"
    },
    "hosts": [
      "dl-cdn.alpinelinux.org",
      "download.docker.com",
      "github.com"
    ]
  },
  "preflight": {
    "rows": [
      "windows-build",
      "virtualization",
      "wsl2",
      "rival-engine",
      "docker-context"
    ]
  },
  "tray": {
    "items": [
      {
        "caption": "Open window",
        "hidden": false
      },
      {
        "caption": "Start engine",
        "hidden": false
      },
      {
        "caption": "Stop engine",
        "hidden": false
      },
      {
        "caption": "Start engine with FreeWilly",
        "hidden": false
      },
      {
        "caption": "Install the update",
        "hidden": true
      },
      {
        "caption": "Quit",
        "hidden": false
      }
    ],
    "visible": 5
  },
  "window": {
    "destinations": [
      "Containers",
      "Images",
      "Volumes",
      "Builds",
      "Engine",
      "About"
    ],
    "machine": 5
  },
  "help": [
    "FreeWilly.exe installs and drives Docker on Windows.",
    "",
    "With no arguments it is the tray icon and the window. Everything else is a console",
    "verb and prints into the terminal it was started from.",
    "",
    "  read <verb>      the agent surface, which mutates nothing",
    "  do <verb>        the agent surface that does",
    "  --tray           the tray icon alone, which is what \"start with Windows\" uses",
    "  --window         accepted, and what a bare launch already does",
    "  --quit           ask the running tray to exit, and wait until it has",
    "  --capture-window <out.png> [tab]",
    "                   render the window to a PNG off-screen, photographing nothing else",
    "  --drive-window [--check]",
    "                   work the real window through UI Automation and print what it says;",
    "                   with --check it drives the filesystem check, which stops Docker",
    "  --show-menu [state] [--seconds n]",
    "                   hold the tray's context menu open, for scripts\\Capture-Window.ps1",
    "  --open-build <link>",
    "                   open one build in the window; this install's handler for the",
    "                   docker-desktop:// link buildx prints at the end of a build",
    "",
    "  --preflight      what this machine can host; add --json for an installer",
    "  --plan           the pinned versions, digests and paths; reaches nothing",
    "  --acquire        download and verify every artefact, and stop",
    "  --provision      acquire, import the distribution, install the engine",
    "",
    "  --run            start the engine and serve the pipe until Ctrl+C",
    "  --stop           stop the engine and terminate the distribution",
    "  --status         what the engine is doing, by asking it",
    "  --fsck           check the distribution's filesystem; --repair to mend what it finds",
    "  --fsck-drill     rehearse the repair on a scratch disk dirtied on purpose, touching",
    "                   nothing on this machine",
    "  --compact-drill  rehearse the compaction on a scratch disk grown and emptied on",
    "                   purpose, touching nothing on this machine",
    "  --api            version and containers, read through the Engine API",
    "  --watch          print /events as they happen, until Ctrl+C",
    "  --autostart      on | off | status  - off unless you turn it on",
    "",
    "  --version        what this build calls itself",
    "  --help           this, and -h does the same",
    "",
    "Exit code 0 means the verb finished; 1 names what stopped it; 2 is an argument",
    "this executable does not have."
  ]
};
