// GENERATED by scripts/surface.mjs from agent-budget.json and the AgentSurface verb
// registry — do not edit by hand. Regenerated on every build (S1, S2): the measured cost
// of the canonical task, the per-shape ceilings a test asserts, and which verbs exist today.
import type { SurfaceData } from "./surface-types";

export const surface: SurfaceData = {
  "baseline": {
    "task": "bring the stack up and say why the api container is not answering",
    "calls": 6,
    "tokens": 11711,
    "shapes": {
      "containers.list": 1906,
      "container.inspect": 1603,
      "container.logs.tail200": 4170,
      "network.inspect": 220
    }
  },
  "target": {
    "calls": 5,
    "tokens": 5000
  },
  "ceilings": {
    "read ports": 120,
    "read ps": 320,
    "do engine": 40,
    "read context": 200,
    "read doctor": 305,
    "read health": 200,
    "read logs": 400,
    "read changes": 115,
    "do reclaim": 170,
    "do compose up": 140,
    "read verify": 240
  },
  "shipped": [
    "read changes",
    "read context",
    "read doctor",
    "read health",
    "read logs",
    "read ports",
    "read ps",
    "read verify",
    "do compose up",
    "do engine",
    "do reclaim"
  ]
};
